---
abstract: 'Memcached storage backend for'
author:
  - 'This module is derived from L<Catalyst::Plugin::Session::FastMmap> code, and'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-Session-Store-Memcached
no_index:
  directory:
    - inc
    - t
requires:
  Cache::Memcached::Managed: 0
  Catalyst::Plugin::Session: 0.26
  MRO::Compat: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-Session-Store-Memcached/
version: 0.04
