---
name: Catalyst-Plugin-Session-Store-Memcached
version: 0.01
author: ~
abstract: |-
  Memcached storage backend for
  session data.
license: perl
requires:
  Cache::Memcached::Managed: 0
  Catalyst::Plugin::Session: 0.01
provides:
  Catalyst::Plugin::Session::Store::Memcached:
    file: lib/Catalyst/Plugin/Session/Store/Memcached.pm
    version: 0.01
generated_by: Module::Build version 0.2611
